services:
  minio:
    image: minio/minio
    container_name: minio-server
    ports:
      - "9000:9000"     # Puerto para la API (lo que usará Java)
      - "9001:9001"     # Puerto para la Consola (lo que verás en el navegador)
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube-server
    ports:
      - "9005:9000" # Usamos el 9005 para no chocar con el API de MinIO