spring.application.name=Imagenes
# Configuración de base de datos Neon
spring.datasource.url=jdbc:postgresql://localhost:5432/neondb
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update

# Configuración personalizada de MinIO
minio.url=http://localhost:9000
minio.accessKey=minioadmin
minio.secretKey=minioadmin
minio.bucket=imagenes-reto